### ISSUE TITLE
Some files not being downloaded because of cooldown

### ISSUE THREAD

**Issue by dxdvostfr** [mysteryengineer/coomer-downloader#2]
Looking at the report.md, I can see that two files haven't been downloaded because of Error - HTTP 429 (too many requests). 
![notepad_aGf3l0MfUC](https://github.com/mysteryengineer/coomer-downloader/assets/49651963/e9459430-ec59-406a-8003-39c0405ca558)

Upon checking the urls, the files do exist, but coomer has limited ressources and prevent how many many requests can be completed in a certain timeframe (explaining the error 429).

It would be great if coomer-dl, when stumbling upon an error 429, could wait some time then retry to download the file, instead of skipping it and adding it to the report.

**Comment by vegidio** [comment]
> It would be great if coomer-dl, when stumbling upon an error 429, could wait some time then retry to download the file, instead of skipping it and adding it to the report.

**coomer-dl** already does this. When a download fails the app waits 5 seconds and then try again later; it repeats this process of waiting and trying again 3 times. But if after 3 times it's still failing then it will give up and add the file to the report.

If you are getting these errors too often, then I suggest to download the number of parallel downloads to minimize the chance of happening. By default **coomer-dl** tries to download 3 files in parallel, but you can tweak this by adding the parameter `--parallel value` (or env variable `$COOMER_PARALLEL` if you're using the Docker version).

Try with 2 or even 1 downloads in parallel and see of what happens. The download process will take longer but you'll get error 429 less often.

**Comment by vegidio** [comment]
This can probably be done, however I will be honest: this is very low in my priority list, since this problem can be minimized by decreasing the number of parallel downloads.

I'm currently working on a GUI for the downloader. When that work is done I might revisit this idea.

**Comment by vegidio** [comment]
FYI, I found a way to minimize the failed download of media files from Coomer, however I will **not** implement this fix here. 

While I was working on the GUI for the downloader I decided to create a brand new project that will download media not only from Coomer, but other websites. When that app is released I will incorporate the improvements for failed downloads.

If you want you can follow the development of that other app [here](https://github.com/vegidio/umd-app). It should be ready in a month or so.
