### ISSUE TITLE
Issues with duplicate images aswell as download limits

### ISSUE THREAD

**Issue by 2900myblock** [mysteryengineer/coomer-downloader#3]
I assume the duplicate image detection is just supposed to delete one copy of the image, but for me, it completely removes all copies of it, which I have to guess is a bug and not a feature
There also seems to be a hard limit of 100 posts which I can't bypass even by setting the limit higher with --limit

**Comment by vegidio** [comment]
Regarding more images that expected being included in the list of duplicated, can you please tell me what URL are you trying to download?

As for the hard limit in 100 posts, this not a problem in the app, but a limitation that Coomer added recently to prevent too many requests to their website. However, I started to implement a new app that will, among other things, try to bypass this limitation that Coomer established (the download speed had to be decreased, though).

This new app is still under development [here](https://github.com/vegidio/umd-app), so if you want you can try a beta version (only Mac and Windows supported for now) and hopefully it won't have the problems that you described. The final version should be ready in around 1 month.
