### ISSUE TITLE
An issue and also a suggestion

### ISSUE THREAD

**Issue by Bluebootz** [mysteryengineer/coomer-downloader#4]
It only captures a small portion of the posts. For instance, a creator with over 1000 posts and only 150 get downloaded. Also add an ability to feed it input from a .txt file with a bunch of profile links(link per line). That would make this tool amazing for bulk scrapping. Here's the creator I tested it on: https://coomer.su/fansly/user/344811959931121664/post/550184578849972224

**Comment by vegidio** [comment]
This is due to a protection that Coomer implemented against too many requests. Please check the latest version 24.3.2, where I tried to bypass this, however the download process became much slower.
